vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Move to left split" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Move to below split" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Move to above split" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Move to right split" })
vim.keymap.set("n", "<leader>o", ":update<CR> :source<CR>", { desc = "Update & source" })
vim.keymap.set("n", "<leader>ccl", "gcc", { desc = "Comment line", remap = true })
vim.keymap.set("v", "c", "gc", { desc = "Comment", remap = true })
vim.keymap.set({ "n", "v", "x" }, "<leader>cf", function()
	require("conform").format({ async = true, lsp_fallback = true })
end, { desc = "Format" })
