# Font
font_family JetBrainsMono Nerd Font Mono
font_size 14.0
disable_ligatures never

# Cursor
cursor_shape beam
cursor_trail 4
cursor_trail_decay 0.2 0.5
cursor_trail_start_threshold 2

# Keybindings
map shift+enter send_text all \n
map ctrl+shift+f2 launch --type=os-window --env PATH=/Users/walter.kennedy/.local/share/bob/nvim-bin:/opt/homebrew/bin:/usr/bin:/bin nvim ~/.config/kitty/kitty.conf

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# macOS
macos_option_as_alt yes
macos_titlebar_color background
