# Font
font_family JetBrainsMono Nerd Font Mono
font_size 13.0
disable_ligatures never

# Theme
include tokyonight.conf

# Cursor
cursor_shape beam
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Keybindings
map shift+enter send_text all \n

# Shell
shell /opt/homebrew/bin/tmux new-session

# macOS
macos_option_as_alt yes
macos_titlebar_color background
